namespace Cockpit.App.ViewModels;

/// <summary>
/// Voices offered by the Options → Voice → Assistant voice-picker. SupertonicTTS is one multilingual model whose
/// speakers are selected by sid, so a "voice" here is a speaker choice rather than a separate per-language model;
/// the same voice speaks both languages (language is passed per utterance, not by switching voice).
/// </summary>
/// <remarks>
/// <b>Measured, not assumed.</b> A throwaway probe (<c>OfflineTts.NumSpeakers</c>) against the downloaded model
/// reported <b>10 speakers (sid 0–9)</b> on <b>2026-08-02</b>, model
/// <c>sherpa-onnx-supertonic-3-tts-int8-2026-05-11</c> (org.k2fsa.sherpa.onnx 1.13.4). All ten synthesised a
/// Dutch+English test clip in roughly the same time (1.7–2.3 s for both sentences together on this machine), so
/// none was excluded as too slow. This count is a fact about that model build on that date — it is not re-checked
/// at build or run time, so a future model swap needs a re-measure and an update here, not an assumption that it
/// still holds.
/// <para>
/// <b>Where the names come from.</b> Upstream ships ten named styles, and the sid is not arbitrary: sherpa-onnx's
/// <c>scripts/supertonic/generate_voices_bin.py</c> builds <c>voice.bin</c> from
/// <c>sorted(input_dir.glob("*.json"))</c> and prints <c>sid 0..n-1</c>, and the input directory is a clone of
/// Hugging Face <c>Supertone/supertonic-3</c>, whose <c>voice_styles/</c> holds exactly
/// <c>F1..F5, M1..M5</c>. Sorting those ten filenames gives F1&lt;F2&lt;F3&lt;F4&lt;F5&lt;M1&lt;M2&lt;M3&lt;M4&lt;M5, so sid 0–4 are the
/// female styles and 5–9 the male ones. The descriptions are quoted from Supertone's own voices page rather than
/// written here, so nothing claims a character the model does not advertise.
/// </para>
/// <para>
/// ⚠️ <b>The one thing not verified:</b> that this published model build was generated by that script without
/// deviation — the bytes of <c>voice.bin</c> were never recomputed from the JSON styles and compared. The build
/// recipe, the source file list and the sid convention were each read at the source; the last link is inference.
/// If a voice ever sounds like the opposite of its label, that inference is where it broke. And it takes the
/// descriptions with it, not just the order: each is quoted at the source, but <em>which</em> quote belongs to
/// which sid is decided entirely by that same sorted-filename step, so an off-by-one there hands every voice in
/// the picker a sentence that is perfectly accurate about a different one. "Quoted rather than written here" is a
/// claim about the words; it is not a second, independent check on the pairing.
/// </para>
/// </remarks>
public static class TtsVoiceCatalog
{
    // Index is the sid, by construction: the position in this array is the number handed to the synthesizer, so a
    // name and its sid cannot drift apart the way the old hand-written pair did ("Voice 2" was sid 3).
    private static readonly string[] _StyleNames =
        ["F1", "F2", "F3", "F4", "F5", "M1", "M2", "M3", "M4", "M5"];

    // Quoted from Supertone's voices page, shortened to what fits a picker. Kept beside the names so the two are
    // read — and corrected — together.
    private static readonly string[] _Descriptions =
    [
        "calm, slightly low",
        "bright and cheerful",
        "clear, announcer-style",
        "crisp and confident",
        "kind and gentle",
        "lively and upbeat",
        "deep and composed",
        "polished, authoritative",
        "soft, neutral-toned",
        "warm, soft-spoken",
    ];

    public static IReadOnlyList<TtsVoiceOption> Voices { get; } =
    [
        .. _StyleNames.Select((name, sid) =>
            new TtsVoiceOption($"{name} — {_Descriptions[sid]}", sid)),
    ];

    /// <summary>sid 1 (F2) — unchanged from before this list grew, so nobody's saved choice moves under them.</summary>
    public static TtsVoiceOption Default { get; } = Voices.Single(voice => voice.Sid == 1);
}
