namespace Cockpit.App.ViewModels;

// Voices offered by the Options → Voice → Assistant voice-picker. SupertonicTTS is one multilingual model whose
// speakers are selected by sid, so a "voice" here is a speaker choice rather than a separate per-language model;
// the same voice speaks both languages (language is passed per utterance, not by switching voice).
// *Measured, not assumed.* A throwaway probe (`OfflineTts.NumSpeakers`) against the downloaded model
// reported *10 speakers (sid 0–9)* on *2026-08-02*, model
// `sherpa-onnx-supertonic-3-tts-int8-2026-05-11` (org.k2fsa.sherpa.onnx 1.13.4). All ten synthesised a
// Dutch+English test clip in roughly the same time (1.7–2.3 s for both sentences together on this machine), so
// none was excluded as too slow. This count is a fact about that model build on that date — it is not re-checked
// at build or run time, so a future model swap needs a re-measure and an update here, not an assumption that it
// still holds.
//
// *Where the names come from.* Upstream ships ten named styles, and the sid is not arbitrary: sherpa-onnx's
// `scripts/supertonic/generate_voices_bin.py` builds `voice.bin` from
// `sorted(input_dir.glob("*.json"))` and prints `sid 0..n-1`, and the input directory is a clone of
// Hugging Face `Supertone/supertonic-3`, whose `voice_styles/` holds exactly
// `F1..F5, M1..M5`. Sorting those ten filenames gives F1&lt;F2&lt;F3&lt;F4&lt;F5&lt;M1&lt;M2&lt;M3&lt;M4&lt;M5, so sid 0–4 are the
// female styles and 5–9 the male ones. The descriptions are quoted from Supertone's own voices page rather than
// written here, so nothing claims a character the model does not advertise.
//
// ⚠️ *The one thing not verified:* that this published model build was generated by that script without
// deviation — the bytes of `voice.bin` were never recomputed from the JSON styles and compared. The build
// recipe, the source file list and the sid convention were each read at the source; the last link is inference.
// If a voice ever sounds like the opposite of its label, that inference is where it broke. And it takes the
// descriptions with it, not just the order: each is quoted at the source, but *which* quote belongs to
// which sid is decided entirely by that same sorted-filename step, so an off-by-one there hands every voice in
// the picker a sentence that is perfectly accurate about a different one. "Quoted rather than written here" is a
// claim about the words; it is not a second, independent check on the pairing.
public static class TtsVoiceCatalog
{
    // Index is the sid, by construction: the position in this array is the number handed to the synthesizer, so a
    // name and its sid cannot drift apart the way the old hand-written pair did ("Voice 2" was sid 3).
    private static readonly string[] _StyleNames =
        ["F1", "F2", "F3", "F4", "F5", "M1", "M2", "M3", "M4", "M5"];

    // Quoted from Supertone's voices page, shortened to what fits a picker. Kept beside the names so the two are
    // read — and corrected — together.
    private static readonly string[] _Descriptions =
    [
        "calm, slightly low",
        "bright and cheerful",
        "clear, announcer-style",
        "crisp and confident",
        "kind and gentle",
        "lively and upbeat",
        "deep and composed",
        "polished, authoritative",
        "soft, neutral-toned",
        "warm, soft-spoken",
    ];

    public static IReadOnlyList<TtsVoiceOption> Voices { get; } =
    [
        .. _StyleNames.Select((name, sid) =>
            new TtsVoiceOption($"{name} — {_Descriptions[sid]}", sid)),
    ];

    // sid 1 (F2) — unchanged from before this list grew, so nobody's saved choice moves under them.
    public static TtsVoiceOption Default { get; } = Voices.Single(voice => voice.Sid == 1);
}
